apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: MONGODB_HOST
              value: db
          image: app:1.0.0
          name: app
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: app
  name: app
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: app

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  serviceName: db
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      containers:
        - name: db
          image: mongo:5.0.23
          imagePullPolicy: Never
          command: ["/bin/sh"]
          args: ["-c", "mongod --replSet=rs0 --bind_ip_all"]
          resources:
            limits:
              cpu: "1"
              memory: 1500Mi
            requests:
              cpu: "1"
              memory: 1000Mi
          ports:
          - name: db 
            containerPort: 27017
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: db

